### ISSUE TITLE
Build documentation in CI

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/aesara#126]
We should start automatically building the documentation in CI, then we can keep our https://theano-pymc.readthedocs.io/ site up-to-date and start linking to it.

**Comment by dfm** [comment]
It looks to me like the RTDs page is working. The last build was for your last commit: https://readthedocs.org/projects/theano-pymc/builds/

Is there something missing from those docs?

**Comment by brandonwillard** [comment]
Is that picking up all the docstring/API changes?

**Comment by dfm** [comment]
I believe so, e.g.: https://theano-pymc.readthedocs.io/en/latest/library/tensor/nlinalg.html#theano.tensor.nlinalg.matrix_power

That docstring was added in https://github.com/pymc-devs/Theano-PyMC/commit/6150681097433cb477a778c009180dab35e02d3b (and now I see a typo!)

**Comment by dfm** [comment]
Some of the more major changes (e.g. changing module names, etc.) might require changes to the docs source files, but it looks like it uses automodule throughout so it should be pretty robust.
