### ISSUE TITLE
Rename project to Aesara

### ISSUE THREAD

**Issue by eigenfoo** [pymc-devs/aesara#148]
There's a consensus among the PyMC developers to rename this project to Aesara, after the daughter of Theano and Pythagoras (at least, according to a minor tradition).

I propose the following import bindings, which seem aesthetically pleasing. If there's agreement on these bindings, we might as well set an example and use them in our own imports (e.g. our test suite).

```python
import aesara as ae
import aesara.tensor as aet
```

This will be a large and probably disruptive change:

- [ ] The library itself, but particularly `__init__.py` and `setup.py` must be updated
- [ ] Our test suite will need to use the new name
- [ ] Whatever documentation we have should reference Aesara and not Theano
- [x] The package will have to be re-uploaded to PyPI
- [ ] The GitHub repository itself will also need to be renamed

**Comment by eigenfoo** [comment]
We're name-squatting the `aesara` project on PyPI now: https://pypi.org/project/aesara/. Thanks @twiecki!

**Comment by canyon289** [comment]
Im in favor of these bindings
