### ISSUE TITLE
Remove documentation contents that are no longer relevant to the project

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/aesara#283]
The `/doc` folder contains material such as conference presentations (`cifarSC2011`, `nextml2015`, ...) and `proposals`.
They often include code snippets that became incompatible or have to be refactored.
Some proposals (`mongodb_cache`, ...) are no longer relevant to this project.

We should remove all of this content as it's still archived in https://github.com/Theano/Theano/tree/master/doc

**Comment by Saurav-Sutaria** [comment]
I want to work on this issue, but don't know how to get started. Can you please guide me how to get started, as this is the first issue I am working for.

**Comment by michaelosthege** [comment]
@Saurav-Sutaria how familiar are you with Theano-PyMC ?

**Comment by Saurav-Sutaria** [comment]
not very much familiar with Theano-PyMC

**Comment by michaelosthege** [comment]
@Saurav-Sutaria if you have not worked with Theano and PyMC3 before, this is probably not the right project to start out with.

**Comment by Saurav-Sutaria** [comment]
@michaelosthege Ok, no problem
