### ISSUE TITLE
Replace C-code generation and compilation backend

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/aesara#312]
The text-based C-code generation and compilation backend in Aesara is difficult to use, debug, maintain, and extend.  We need to fix that ASAP.

[Cython](https://cython.org/) is a well established Python-to-C transpiler that provides a much cleaner, automatic means of generating the same kind of Python C API code that's written by hand in Aesara.  Here are some possible benefits to replacing our current C implementations with Cython-generated C code:
- we could make more of our logic transparent to pure-Python readers
- automatically benefit from updates and new features provided by Cython over time (e.g. Python C API version and capability updates)
- use Cython's build and code caching features, which could have much better support for different platforms and environments
- attempt automatic conversion of Python-only `Op` implementations, resulting in more C-only code (i.e. fewer calls to-and-from Python/C during graph evaluation)
- C-level interactions with NumPy are much easier in Cython, so we might&mdash;for example&mdash;be able to generate C code for all the `Subtensor*`/indexing operations with a little bit of Cython (instead of our very limited C implementations for only certain types of indexing)

This general idea has been brought up in numerous different locations, so I'm creating this issue as a means of collecting all the relevant details, ideas, discussions, requirements, etc., into one place.

Related issues:
- #306 
- #129 
- #10

**Comment by twiecki** [comment]
Totally agree. I suppose we first need some functionality to enable usage of Cython.

**Comment by brandonwillard** [comment]
It's not actually that difficult to _use_ Cython-generated code in Aesara right now.  For instance, an `Op` can create its own thunk&mdash;via `Op.make_thunk`&mdash;that calls out to a Cython-generated extension.  This is what [the `Scan` `Op` does](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/scan/op.py#L993).  This is the approach used by the old example referenced in https://github.com/pymc-devs/aesara/issues/10.

My impression is that this approach isn't the best because it doesn't use Aesara's C-based thunk machinery.  This machinery is assumedly faster than the corresponding pure Python machinery, perhaps due to reduced Python-to-C and C-to-Python overhead&mdash;among other things.

There are a few places where the C and Python thunks are clearly distinguished.  In the `CVM` (aka `lazylinker_c.CLazyLinker` from the C extension end), which is generally used whenever the C toolchain is available, C thunks are treated specially (see [here](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/link/c/c_code/lazylinker_c.c#L327)), which sets a variable that signals the use of a special [`CVM.c_call`](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/link/c/c_code/lazylinker_c.c#L699).  There doesn't seem to be much to it, just a pointer to the thunk's C function and that function's data/arguments.

From the Python side (e.g. when graph evaluation is performed using the pure Python `VM` `Stack`), there's a [`_CThunk`](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/link/c/basic.py#L1701) class that appears to do the same thing as the `CVM.c_call` within [`_CThunk.__call__`](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/link/c/basic.py#L1745).  It uses the `run_cthunk` function that's implemented in C [here](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/link/c/cutils.py#L27) and exposed to Python via the `cutils_ext` extension.  Ultimately `run_cthunk` uses the same pointers in the same way as `CVM.c_call`.

From what I can tell, `_CThunk`s are exclusively created by the `CLinker`, which is briefly used by `COp.make_c_thunk` (called from the standard entry point `Op.make_thunk`) to make its thunks.  Aside from the questionable need for an entirely distinct `CLinker` class and/or object in this situation, it seems like the whole situation could be as simple as obtaining&mdash;and using&mdash;those pointers.

Regarding those pointers, the thunk pointers seems to come from [`CLinker.cthunks_factory`](https://github.com/pymc-devs/aesara/blob/16f98e4fd69db92e0c2cde9dd97a0d005235deea/aesara/link/c/basic.py#L1606), which kicks off the C-code compilation process&mdash;the same one that we're considering replacing here (e.g. with Cython, or at least some use of [`distutils`'s compilation code](https://docs.python.org/3/distutils/apiref.html#module-distutils.ccompiler)).  In Python, those thunk pointers are [`PyCapsule` objects](https://docs.python.org/3/c-api/capsule.html), and they can be easily created/accessed in Cython.

**Comment by brandonwillard** [comment]
For anyone who wants to try this (@aseyboldt?), take a look at [how `COp` creates C thunks](https://github.com/pymc-devs/aesara/blob/erfcx_c/aesara/graph/op.py#L552).  I think the relevant parts start [here](https://github.com/pymc-devs/aesara/blob/erfcx_c/aesara/graph/op.py#L597) (i.e. `CLinker.make_thunk`), so we might need to jump into whatever happens there.

**Comment by brandonwillard** [comment]
Actually, it looks like it might be as simple as [creating an `aesara.link.c.basic._CThunk`](https://github.com/pymc-devs/aesara/blob/master/aesara/link/c/basic.py#L1207) object.  In order to do that, we need all of its arguments.

The [`self.__compile__(...)`](https://github.com/pymc-devs/aesara/blob/master/aesara/link/c/basic.py#L1203) step before that is how we get those arguments.  The `cthunk` value returned by `CLinker.__compile__` is a `PyCapsule` object, `module` is a `module`-type object, `in_storage` and `out_storage` are lists of `aesara.link.basic.Container`s, and `error_storage` is just a list of `None`s.  

The first two values (i.e. the `PyModule` and `module` objects) seem obtainable from Cython/Numba, so it looks like we'll only need to reproduce the storage and error array creation steps.
