### ISSUE TITLE
JAX conversion of aet.diag(...) does not work while aet.nlinalg.diag(...) works

### ISSUE THREAD

**Issue by sokol11** [pymc-devs/aesara#313]
I get the `AttributeError: 'Second' object has no attribute 'nfunc_spec'` error when trying to sample my Gaussian Random Walk model with `pm.sampling_jax.sample_numpyro_nuts`. I know that this is an experimental library, so it is probably expected behavior at this point. But if you have some insight into what is going on, please share. Thank you.

**Comment by twiecki** [comment]
@sokol11 Thanks, these reports are very valuable. Can you post the code that triggers this? I have run a model with a GRW successfully in the past (the stoch vol model). Also, are you on master?

**Comment by sokol11** [comment]
Here's the code:

```
with pm.Model() as model:
    
    sigma = pm.HalfCauchy('sigma', 1.)
    alpha = .1
    mu = pm.GaussianRandomWalk('mu', 
                              sigma=sigma * (1. - alpha), 
                              shape=len(y)
                              )
    likelihood = pm.Normal('sales', 
                      mu=mu, 
                      sigma=sigma * alpha, 
                      observed=y
                          )
```

It throws the same error with a multivariate GRW (which is what I really want to run):

```
with pm.Model() as model:
        
    alpha = .3
    mean_sigma = pm.HalfCauchy('mean_rw_sigma', 1., shape=n_timeseries)
    prior_means = pm.MvGaussianRandomWalk(
        'rw',
        mu=np.zeros(n_timeseries),
        chol=tt.diag(mean_sigma),
        shape=(n_timepoint, n_timeseries)
    )
    sd = mean_sigma * alpha
    likelihood = pm.Normal('sales', mu=prior_means, sigma=sd, observed=y)
```

I installed pymc3jax and Theano-PyMC as:

pip install git+https://github.com/pymc-devs/Theano-PyMC.git
pip install git+https://github.com/pymc-devs/pymc3.git@pymc3jax

I also tested the sampler on a simple non-GRW model to ensure that my install works.

Thank you!

**Comment by twiecki** [comment]
Ah, you shouldn't use the pymc3jax branch anymore but just master. I should just delete that branch. Where did you get the info to use that branch?

**Comment by sokol11** [comment]
Ah, silly me. You mean I should just install the latest PyMC3 version `pip install pymc3` and go with that? I think it says to go with pymc3jax in https://docs.pymc.io/notebooks/GLM-hierarchical-jax.html

**Comment by sokol11** [comment]
Ok, I just tried it with a regular PyMC3 install and it works with a single time series GRW model. And it is BLAZING fast!!

Though it does throw this error for the multivariate GRW model: `NotImplementedError: No JAX conversion for the given `Op`: AllocDiag{offset=0, axis1=0, axis2=1}`

Here's the model code:

```
with pm.Model() as model:
        
    alpha = .3
    mean_sigma = pm.HalfCauchy('mean_rw_sigma', 1., shape=n_timeseries)
    prior_means = pm.MvGaussianRandomWalk(
        'rw',
        mu=np.zeros(n_timeseries),
        chol=tt.diag(mean_sigma),
        shape=(n_timepoint, n_timeseries)
    )
    sd = mean_sigma * alpha
    likelihood = pm.Normal('sales', mu=prior_means, sigma=sd, observed=y)
```

Any thoughts? Thank you! This is pretty amazing.

**Comment by twiecki** [comment]
@sokol11 Good to hear it's fast. Odd, `AllocDiag` is implemented: https://github.com/pymc-devs/aesara/blob/c058326d7e7cfa0087c033ada62beb5ea8104258/aesara/link/jax/jax_dispatch.py#L838

Can you check whether that function exists? Otherwise you might want to update to Aesara and PyMC3 master.

**Comment by sokol11** [comment]
Yes, I did not have aesara installed. I tried installing it but it still showed the same error, then I ran:

```
pip uninstall pymc3
pip uninstall theano-pymc
```

Followed by

```
pip install pymc3
pip install aesara
```

It still throws the same error, any ideas what else I can try? Thank you.

**Comment by sokol11** [comment]
Minor update. I think I did not have gcc installed correctly. I actually ended up finally ditching openSUSE and switching to Ubuntu in my attempt to fix the issue. The good news is that the conventional sampler now works about 2x faster. But trying to sample with jax still throws the same error, unfortunately.

**Comment by sokol11** [comment]
UPDATE

I believe it was a namespace issue between theano-PyMC and aesara.

First, I realized I had both theano-PyMC and aesara installed. So, I uninstalled everything and installed PyMC from development master, like so `pip install git+https://github.com/pymc-devs/pymc3`.

After installing from development master, I imported `aesara.tensor as aet` and changed `tt.diag(...)` in my model to `aet.diag(...)`. But the error still persisted!

Finally, I changed `aet.diag(...)` to `aet.nlinalg.diag(...)`, and it worked!

So, it appears that the namespaces do not map exactly between theano-PyMC and aesara. And, of course, it is a bad idea to have both installed.

Interestingly, sampling via `pm.sampling_jax.sample_numpyro_nuts` appears to be slower than with `pm.sample` now (I got 14min vs 10min for my specific model and dataset). So now I wonder if something is still off about my jax install or something. But at least it runs now!

**Comment by twiecki** [comment]
> Finally, I changed aet.diag(...) to aet.nlinalg.diag(...), and it worked!

That is quite odd, you got the same no JAX Op error?

**Comment by sokol11** [comment]
Yep, when I switched to aet.nlinalg.diag, it just compiled and ran (no errors). When I looked at the aesara source code, I saw that the AllocDiag class and diag function are in the nlinalg submodule, so I figured to try it.

**Comment by brandonwillard** [comment]
Here's a MWE:

```python
import pymc3 as pm
import numpy as np
import aesara.tensor as aet
from pymc3.sampling_jax import sample_numpyro_nuts


n_timeseries = 2
n_timepoint = 2
alpha = .3
y = np.random.normal(size=(2, 2))

with pm.Model() as model:
    mean_sigma = pm.HalfCauchy('mean_rw_sigma', 1., shape=n_timeseries)
    prior_means = pm.MvGaussianRandomWalk(
        'rw',
        mu=np.zeros(n_timeseries),
        chol=aet.diag(mean_sigma),
        shape=(n_timepoint, n_timeseries)
    )
    sd = mean_sigma * alpha
    likelihood = pm.Normal('sales', mu=prior_means, sigma=sd, observed=y)


with model:
    hierarchical_trace_jax = sample_numpyro_nuts(2000, tune=2000, target_accept=0.9)
```

The issue is due to the fact that we have two `AllocDiag`s: the one in `aesara.tensor.nlinalg` was deprecated and needs to be removed.
