### ISSUE TITLE
Add `dtype` option to `as_tensor_variable`

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/aesara#369]
As commented by @brandonwillard in https://github.com/pymc-devs/aesara/pull/367#pullrequestreview-633036110 - please edit to add more information/context if applicable.

`as_tensor_variable` is kinda like the Aesara equivalent for `np.array`.

A `dtype` option would make a lot of code more concise.
It does raise the question whether there should be settings to configure casting behavior:
+ of non-`Variables`
+ of `Variables` to a different dtype

**Comment by brandonwillard** [comment]
> It does raise the question whether there should be settings to configure casting behavior:

Yes, there is a general lack of specificity when it comes to dtype conversions.  For instance, [`TensorType.filter`](https://github.com/pymc-devs/aesara/blob/master/aesara/tensor/type.py#L100) has `strict` and `allow_downcast` options, but not one that prevents cross-type conversions: e.g. `strict=True` will prevent upcasting an `int32` to `int64`, so it's too strict, and `strict=False` will allow casting a `float64` to a `int64`, which is too permissive.
