### ISSUE TITLE
Move `aesara.tensor.nnet.sigm` to `aesara.[scalar|tensor].*`

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/aesara#378]
The `Op`s and optimizations in `aesara.tensor.nnet.sigm` belong in `aesara.tensor.*`, `aesara.scalar.*`, etc.  

More specifically, the `UnaryScalarOp`s (e.g. [`Sigmoid`](https://github.com/pymc-devs/aesara/blob/master/aesara/tensor/nnet/sigm.py#L29)) belong in `aesara.scalar.basic_scipy`, the corresponding `Elemwise`s belong in `aesara.tensor.math` (e.g. [`sigmoid`](https://github.com/pymc-devs/aesara/blob/master/aesara/tensor/nnet/sigm.py#L180)), the inplace `Elemwise`s belong in `aesara.tensor.inplace` (e.g. [`sigmoid_inplace`](https://github.com/pymc-devs/aesara/blob/master/aesara/tensor/nnet/sigm.py#L182)), and the optimizations belong in `aesara.tensor.math_opt` (e.g. [`local_ultra_fast_sigmoid`](https://github.com/pymc-devs/aesara/blob/master/aesara/tensor/nnet/sigm.py#L268)). 

We also need to be able to access these `Op`s via their SciPy names (e.g. `expit = sigmoid`).

**Comment by ricardoV94** [comment]
> We also need to be able to access these Ops via their SciPy names (e.g. expit = sigmoid).

What do you mean by this? Rename the actual op?

**Comment by brandonwillard** [comment]
> Or create an alias

Yeah, an alias is fine.
