### ISSUE TITLE
Expose `aesara.tensor.random.basic` via `aesara.random`

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/aesara#428]
To make it easier to use the `RandomVariable`s in `aesara.tensor.random.basic`, we should expose the module via `aesara.random` so that it more closely follows `np.random`.

**Comment by ricardoV94** [comment]
Do we want the name of the distributions to be the same as in numpy as well? IIRC in aesara we have `nbinom` but in numpy it is called `negative_binomial`. There might be some others like this.

**Comment by brandonwillard** [comment]
> Do we want the name of the distributions to be the same as in numpy as well? IIRC in aesara we have `nbinom` but in numpy it is called `negative_binomial`. There might be some others like this.

Yeah, as long as it's easy (e.g. adding aliases), let's make it match NumPy.
